# Generated by Django 3.1.4 on 2020-12-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_publicado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
